#!/bin/bash
# Script attempts to enable a network interface into monitor mode.
# Note: Must be run with super user privileges
# does accept params for monitor and channel, but defaults to mon0 and 3
dev=${1:-mon0}
chan=${2:-3}
echo dev: $dev
echo chan: $chan
set -x
{
  ip link set $dev down && \
  iw dev $dev set monitor fcsfail otherbss && \
  ip link set $dev up && \
  iw dev $dev set channel $chan && \
  iw dev $dev info 
} || {
  echo "setting monitor mode failed, reverting back to managed mode..." && \
  ip link set $dev down && \
  iw dev $dev set type managed && \
  ip link set $dev up && \
  iw dev $dev info;
  exit 1
}
exit 0
